<?php

namespace Renderbit\LaravelWhatsapp\Constants;

class ErrorCodes
{
    public const MAP = [
        28694 => 'Invalid template parameters',
        10001 => 'Invalid phone number',
        52992 => 'Username / Password incorrect',
        52995 => 'Daily Credit limit Reached',
        57089 => 'Contract expired',
        57090 => 'User credit expired',
        57091 => 'User disabled',
        65280 => 'Service is temporarily unavailable',
        65535 => 'The specified message does not conform to DTD',
        28673 => 'Destination number not numeric',
        28674 => 'Destination number empty',
        28675 => 'Sender address empty',
        28676 => 'Template mismatch',
        28679 => 'SMS text is empty',
        28680 => 'Invalid sender ID',
        28681 => 'Invalid message, Duplicate message, Submit failed',
        28682 => 'Invalid Receiver ID',
        28683 => 'Invalid Date time for message Schedule',
        28684 => 'Invalid SMS Block',
        28692 => 'Invalid Split Count',
        28695 => 'Template matched but invalid variables in template.',
        28696 => 'Media ID, type, content type cannot be null or blank in case of two way media message. If text have data, it should be in base64 format.',
        28697 => 'Incorrect User Route',
        28698 => 'Invalid/Blank Media data or type(In case of Push Media Message)',
        28699 => 'MSGTYPE in WhatsApp Data Request Packet is empty.',
        28700 => 'WhatsApp Data Request Packet is Empty / Media type in WhatsApp data request packet does not match with the MSGTYPE received in the request.',
        28702 => 'Invalid DLT Parameters',
        28703 => 'Invalid DLT Content Type',
        28704 => 'Invalid Authorization Type',
        28678 => 'Coding is invalid',
        2009 => 'Required component in the Template is missing',
        2010 => 'URL in button component is invalid',
        2011 => 'Phone Number in button component is invalid',
        2012 => 'Parameter format does not match format in the created Template',
        2022 => 'WEBENAGE_TEMPLATE_PARAMETER_FORMAT_MISMATCH',
        2026 => 'WEBENAGE_UNSUPPORTED_TEMPLATE_LANGUAGE',
        9988 => 'WEBENAGE_UNKNOWN_FAILURE',
        28685 => 'ADDRESS_BLOCK_INVALID',
        28686 => 'SPAM_MESSAGE',
        28687 => 'DROP_MESSAGE',
        28688 => 'DUMP_MESSAGE',
        28689 => 'SUBSCRIBER_OPTED_OUT',
        28690 => 'TO_EMAIL_ADDRESS_EMPTY',
        28691 => 'INVALID_TO_EMAIL_ADDRESS',
        28693 => 'OPT_OUT',
        28701 => 'MANDATE_PARAMETER_MISSING',
        38679 => 'CAMPAIGN_ID_EMPTY',
        38681 => 'INVALID_NODES',
        52993 => 'INVALID_HG_USER_VALIDATION',
        52994 => 'INVALID_API_KEY_VALIDATION',
        65536 => 'INVALID_JSON',
    ];
}
